# -*- coding: utf-8 -*-
"""predicting_company_profits_MLR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f_ePSEv3Z_V_ij9Nf0nLuOjxNAfNvdFW
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#import dataset

dataset=pd.read_csv('50_Startups.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

#splitting the dataset into train and test sets

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

print(x_train)

print(y_train)

#training the model using multiple linear regression model on training set
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

y_pred

y_test

np.set_printoptions(precision=2)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

#on training data

plt.scatter(x_train[:,4:5],y_train,color="red")
plt.scatter(x_train[:,4:5],lr.predict(x_train),color="blue")
plt.xlabel('Administration Amount')
plt.ylabel('profits')
plt.show()

x_train[:,4:5]

y_train

#on testing data

plt.scatter(x_test[:,4:5],y_test,color="red")
plt.scatter(x_test[:,4:5],lr.predict(x_test),color="blue")
plt.xlabel('Administration Amount')
plt.ylabel('profits')
plt.show()

